### PR TITLE
added historical comparison to dapp reports

### PR DESCRIPTION
**Pull request by IvanAdamovNeon**

### CODE REVIEW

**Comment by neonlabstech** [comment]
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getSlot                           |   34221 |      0     |      0.028 |    0.000511762 |        0      |
| getBlocks                         |   16861 |      0     |      0.154 |    0.000539351 |        0      |
| getBlock                          |   10805 |      0     |      0.026 |    0.00118917  |        0.001  |
| getAccountInfo                    |    8558 |      0     |      0.037 |    0.00129832  |        0      |
| getLatestBlockhash                |    5430 |      0     |      0.072 |    0.000437201 |        0      |
| getTransaction                    |    1977 |      0     |      0.018 |    0.00244815  |        0.002  |
| getMultipleAccounts               |    1745 |      0     |      0.011 |    0.000861891 |        0.001  |
| sendTransaction                   |    1181 |      0     |      0.061 |    0.00275614  |        0.002  |
| getBlockTime                      |     739 |      0     |      0.001 |    0.000239513 |        0      |
| getBalance                        |     374 |      0     |      0.001 |    0.000387701 |        0      |
| getSignatureStatuses              |     120 |      0     |      0.001 |    0.000433333 |        0      |
| getVersion                        |      84 |      0     |      0.014 |    0.000535714 |        0      |
| isBlockhashValid                  |      42 |      0     |      0.001 |    0.000119048 |        0      |
| simulateTransaction               |      38 |      0     |      0.001 |    0.000394737 |        0      |
| getSignaturesForAddress           |      35 |      0     |      0.003 |    0.00114286  |        0.001  |
| requestAirdrop                    |      32 |      0     |      0.001 |    0.00078125  |        0.001  |
| getTokenAccountBalance            |       3 |      0     |      0.001 |    0.000666667 |        0.001  |
| getFirstAvailableBlock            |       2 |      0     |      0.001 |    0.0005      |        0.0005 |
| getHealth                         |       1 |      0.001 |      0.001 |    0.001       |        0.001  |
| getMinimumBalanceForRentExemption |       1 |      0     |      0     |    0           |        0      |

</details>

**Comment by neonlabstech** [comment]
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getSlot                           |   33850 |      0     |      0.046 |    0.000610222 |        0      |
| getBlocks                         |   16503 |      0     |      0.03  |    0.000611525 |        0.001  |
| getBlock                          |   10619 |      0     |      0.029 |    0.00142942  |        0.001  |
| getAccountInfo                    |    8521 |      0     |      0.036 |    0.00179862  |        0      |
| getLatestBlockhash                |    5367 |      0     |      0.027 |    0.000553568 |        0      |
| getTransaction                    |    1966 |      0     |      0.03  |    0.00326907  |        0.002  |
| getMultipleAccounts               |    1723 |      0     |      0.023 |    0.00116831  |        0.001  |
| sendTransaction                   |    1179 |      0     |      0.066 |    0.00377778  |        0.002  |
| getBlockTime                      |     729 |      0     |      0.001 |    0.00033059  |        0      |
| getBalance                        |     374 |      0     |      0.002 |    0.000350267 |        0      |
| getSignatureStatuses              |     120 |      0     |      0.003 |    0.0005      |        0      |
| getVersion                        |      84 |      0     |      0.001 |    0.000297619 |        0      |
| isBlockhashValid                  |      42 |      0     |      0.001 |    0.000380952 |        0      |
| simulateTransaction               |      38 |      0     |      0.001 |    0.000289474 |        0      |
| getSignaturesForAddress           |      36 |      0     |      0.003 |    0.00125     |        0.001  |
| requestAirdrop                    |      32 |      0     |      0.002 |    0.0009375   |        0.001  |
| getTokenAccountBalance            |       3 |      0     |      0     |    0           |        0      |
| getFirstAvailableBlock            |       2 |      0     |      0.001 |    0.0005      |        0.0005 |
| getHealth                         |       1 |      0.001 |      0.001 |    0.001       |        0.001  |
| getMinimumBalanceForRentExemption |       1 |      0     |      0     |    0           |        0      |

</details>

**Comment by neonlabstech** [comment]
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getSlot                           |   30639 |          0 |      0.154 |    0.000574594 |        0      |
| getBlocks                         |   14479 |          0 |      0.03  |    0.000590718 |        0      |
| getBlock                          |    9266 |          0 |      0.026 |    0.00128275  |        0.001  |
| getAccountInfo                    |    8366 |          0 |      0.033 |    0.00157076  |        0      |
| getLatestBlockhash                |    4843 |          0 |      0.026 |    0.000405121 |        0      |
| getTransaction                    |    1965 |          0 |      0.016 |    0.00258626  |        0.002  |
| getMultipleAccounts               |    1683 |          0 |      0.007 |    0.000996435 |        0.001  |
| sendTransaction                   |    1178 |          0 |      0.046 |    0.00313837  |        0.002  |
| getBlockTime                      |     710 |          0 |      0.002 |    0.00028169  |        0      |
| getBalance                        |     374 |          0 |      0.015 |    0.000454545 |        0      |
| getSignatureStatuses              |     120 |          0 |      0.001 |    0.0005      |        0.0005 |
| getVersion                        |      84 |          0 |      0.001 |    0.000309524 |        0      |
| isBlockhashValid                  |      42 |          0 |      0.001 |    0.000404762 |        0      |
| simulateTransaction               |      38 |          0 |      0.001 |    0.000657895 |        0.001  |
| getSignaturesForAddress           |      37 |          0 |      0.003 |    0.00113514  |        0.001  |
| requestAirdrop                    |      32 |          0 |      0.002 |    0.0008125   |        0.001  |
| getTokenAccountBalance            |       3 |          0 |      0.001 |    0.000333333 |        0      |
| getFirstAvailableBlock            |       2 |          0 |      0.001 |    0.0005      |        0.0005 |
| getHealth                         |       1 |          0 |      0     |    0           |        0      |
| getMinimumBalanceForRentExemption |       1 |          0 |      0     |    0           |        0      |

</details>

**Comment by neonlabstech** [comment]
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getSlot                           |   29856 |      0     |      0.025 |    0.000535336 |        0      |
| getBlocks                         |   13992 |      0     |      0.029 |    0.000550314 |        0      |
| getBlock                          |    9073 |      0     |      0.02  |    0.00113424  |        0.001  |
| getAccountInfo                    |    8344 |      0     |      0.029 |    0.00123466  |        0      |
| getLatestBlockhash                |    4765 |      0     |      0.017 |    0.000376705 |        0      |
| getTransaction                    |    1958 |      0     |      0.017 |    0.00235036  |        0.002  |
| getMultipleAccounts               |    1681 |      0     |      0.016 |    0.000879239 |        0.001  |
| sendTransaction                   |    1176 |      0     |      0.043 |    0.00265306  |        0.002  |
| getBlockTime                      |     709 |      0     |      0.001 |    0.000238364 |        0      |
| getBalance                        |     374 |      0     |      0.012 |    0.000339572 |        0      |
| getSignatureStatuses              |     120 |      0     |      0.001 |    0.000325    |        0      |
| getVersion                        |      84 |      0     |      0.001 |    0.00022619  |        0      |
| isBlockhashValid                  |      42 |      0     |      0.001 |    0.000404762 |        0      |
| simulateTransaction               |      38 |      0     |      0.001 |    0.000473684 |        0      |
| getSignaturesForAddress           |      38 |      0     |      0.002 |    0.000947368 |        0.001  |
| requestAirdrop                    |      32 |      0     |      0.001 |    0.0006875   |        0.001  |
| getTokenAccountBalance            |       3 |      0     |      0     |    0           |        0      |
| getFirstAvailableBlock            |       2 |      0     |      0.001 |    0.0005      |        0.0005 |
| getHealth                         |       1 |      0.001 |      0.001 |    0.001       |        0.001  |
| getMinimumBalanceForRentExemption |       1 |      0.001 |      0.001 |    0.001       |        0.001  |

</details>

**Review by kristinaNikolaevaa — APPROVED** [review]

**Pull request merged**
