### PR TITLE
Support holder as a heap in evm instructions.

### PR DESCRIPTION
**Pull request by evgenyzdanovich**
Support holder as a heap in evm instructions.

non-iterative transactions - TxExecFromData and TxExecFromDataSolanaCall require holder account placed first in the account list.

### CODE REVIEW

**Comment by neonlabstech** [comment]
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getSlot                           |   70235 |      0     |      0.124 |    0.00111494  |         0.001 |
| getAccountInfo                    |   56227 |      0     |      0.177 |    0.00220752  |         0.001 |
| getBlocks                         |   28445 |      0     |      0.086 |    0.000683916 |         0.001 |
| getBlock                          |   14304 |      0     |      0.072 |    0.00158949  |         0.001 |
| getMultipleAccounts               |   12991 |      0     |      0.181 |    0.00259857  |         0.001 |
| getTransaction                    |    7480 |      0     |      0.182 |    0.0125213   |         0.004 |
| getBlockTime                      |    6076 |      0     |      0.126 |    0.000972515 |         0     |
| sendTransaction                   |    4946 |      0     |      0.179 |    0.0104296   |         0.005 |
| getLatestBlockhash                |    4713 |      0     |      0.126 |    0.00284744  |         0.001 |
| getBalance                        |    1772 |      0     |      0.181 |    0.00247968  |         0.001 |
| getSignatureStatuses              |    1067 |      0     |      0.127 |    0.00244049  |         0.001 |
| getVersion                        |     558 |      0     |      0.027 |    0.00203047  |         0.001 |
| isBlockhashValid                  |     515 |      0     |      0.026 |    0.000691262 |         0     |
| getSignaturesForAddress           |      61 |      0     |      0.004 |    0.00155738  |         0.001 |
| simulateTransaction               |      38 |      0     |      0.001 |    0.000657895 |         0.001 |
| requestAirdrop                    |      32 |      0.001 |      0.002 |    0.001125    |         0.001 |
| getHealth                         |       3 |      0     |      0.001 |    0.000333333 |         0     |
| getTokenAccountBalance            |       3 |      0     |      0.001 |    0.000333333 |         0     |
| getFirstAvailableBlock            |       2 |      0.001 |      0.001 |    0.001       |         0.001 |
| getMinimumBalanceForRentExemption |       1 |      0     |      0     |    0           |         0     |
| getClusterNodes                   |       1 |      0     |      0     |    0           |         0     |

</details>

**Review by afalaleev — COMMENTED** [review]
I have only one comment.
Please, increase the protocol version on this PR.

**Comment by neonlabstech** [comment]
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getSlot                           |   72918 |      0     |      0.126 |    0.00073643  |         0     |
| getAccountInfo                    |   56316 |      0     |      0.123 |    0.00138362  |         0     |
| getBlocks                         |   28071 |      0     |      0.04  |    0.000460404 |         0     |
| getBlock                          |   14138 |      0     |      0.026 |    0.00102942  |         0.001 |
| getMultipleAccounts               |   13273 |      0     |      0.077 |    0.00189384  |         0.001 |
| getTransaction                    |    8010 |      0     |      0.122 |    0.00882147  |         0.003 |
| getBlockTime                      |    6158 |      0     |      0.044 |    0.000555213 |         0     |
| sendTransaction                   |    5174 |      0     |      0.128 |    0.0082126   |         0.004 |
| getLatestBlockhash                |    4953 |      0     |      0.086 |    0.00259055  |         0.001 |
| getBalance                        |    1820 |      0     |      0.043 |    0.00146099  |         0.001 |
| getSignatureStatuses              |    1088 |      0     |      0.073 |    0.00117923  |         0     |
| getVersion                        |     568 |      0     |      0.077 |    0.00150176  |         0     |
| isBlockhashValid                  |     526 |      0     |      0.006 |    0.000353612 |         0     |
| getSignaturesForAddress           |      60 |      0     |      0.014 |    0.00115     |         0.001 |
| simulateTransaction               |      38 |      0     |      0.001 |    0.000368421 |         0     |
| requestAirdrop                    |      32 |      0     |      0.002 |    0.00090625  |         0.001 |
| getHealth                         |       3 |      0     |      0.001 |    0.000333333 |         0     |
| getTokenAccountBalance            |       3 |      0     |      0.001 |    0.000333333 |         0     |
| getFirstAvailableBlock            |       2 |      0.001 |      0.001 |    0.001       |         0.001 |
| getMinimumBalanceForRentExemption |       1 |      0.001 |      0.001 |    0.001       |         0.001 |
| getClusterNodes                   |       1 |      0.001 |      0.001 |    0.001       |         0.001 |

</details>

**Comment by neonlabstech** [comment]
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getAccountInfo                    |   58278 |      0     |      0.208 |    0.00185408  |        0.001  |
| getSlot                           |   57077 |      0     |      0.157 |    0.00112855  |        0.001  |
| getBlocks                         |   22967 |      0     |      0.031 |    0.000704837 |        0.001  |
| getBlock                          |   14795 |      0     |      0.042 |    0.00168043  |        0.001  |
| getMultipleAccounts               |   13620 |      0     |      0.315 |    0.00254567  |        0.001  |
| getTransaction                    |    8038 |      0     |      0.316 |    0.0123777   |        0.005  |
| getBlockTime                      |    6322 |      0     |      0.136 |    0.000692661 |        0      |
| sendTransaction                   |    5181 |      0     |      0.122 |    0.00907759  |        0.004  |
| getLatestBlockhash                |    4983 |      0     |      0.136 |    0.00303793  |        0.001  |
| getBalance                        |    1819 |      0     |      0.049 |    0.00180319  |        0.001  |
| getSignatureStatuses              |    1108 |      0     |      0.154 |    0.00189531  |        0.001  |
| getVersion                        |     578 |      0     |      0.03  |    0.00163322  |        0      |
| isBlockhashValid                  |     536 |      0     |      0.019 |    0.00048694  |        0      |
| getSignaturesForAddress           |      66 |      0     |      0.027 |    0.00274242  |        0.002  |
| simulateTransaction               |      38 |      0     |      0.001 |    0.000605263 |        0.001  |
| requestAirdrop                    |      32 |      0     |      0.001 |    0.00075     |        0.001  |
| getHealth                         |       3 |      0     |      0.006 |    0.003       |        0.003  |
| getTokenAccountBalance            |       3 |      0     |      0     |    0           |        0      |
| getFirstAvailableBlock            |       2 |      0     |      0.001 |    0.0005      |        0.0005 |
| getMinimumBalanceForRentExemption |       1 |      0     |      0     |    0           |        0      |
| getClusterNodes                   |       1 |      0.041 |      0.041 |    0.041       |        0.041  |

</details>

**Review by afalaleev — APPROVED** [review]

**Comment by neonlabstech** [comment]
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getSlot                           |   62292 |      0     |      0.189 |    0.000884191 |         0     |
| getAccountInfo                    |   58447 |      0     |      0.1   |    0.00154413  |         0     |
| getBlocks                         |   25097 |      0     |      0.068 |    0.000653783 |         0     |
| getBlock                          |   16302 |      0     |      0.06  |    0.00135014  |         0.001 |
| getMultipleAccounts               |   13916 |      0     |      0.129 |    0.00195811  |         0.001 |
| getTransaction                    |    8112 |      0     |      0.129 |    0.0098734   |         0.004 |
| getBlockTime                      |    6216 |      0     |      0.067 |    0.000588481 |         0     |
| sendTransaction                   |    5202 |      0     |      0.139 |    0.00731219  |         0.003 |
| getLatestBlockhash                |    4998 |      0     |      0.11  |    0.00223029  |         0.001 |
| getBalance                        |    1826 |      0     |      0.096 |    0.00170044  |         0.001 |
| getSignatureStatuses              |    1091 |      0     |      0.039 |    0.0012044   |         0     |
| getVersion                        |     570 |      0     |      0.093 |    0.00167018  |         0     |
| isBlockhashValid                  |     527 |      0     |      0.017 |    0.000512334 |         0     |
| getSignaturesForAddress           |      61 |      0     |      0.007 |    0.0015082   |         0.001 |
| simulateTransaction               |      38 |      0     |      0.001 |    0.000394737 |         0     |
| requestAirdrop                    |      32 |      0     |      0.001 |    0.00078125  |         0.001 |
| getHealth                         |       3 |      0     |      0.001 |    0.000333333 |         0     |
| getTokenAccountBalance            |       3 |      0     |      0     |    0           |         0     |
| getFirstAvailableBlock            |       2 |      0.001 |      0.001 |    0.001       |         0.001 |
| getMinimumBalanceForRentExemption |       1 |      0     |      0     |    0           |         0     |
| getClusterNodes                   |       1 |      0     |      0     |    0           |         0     |

</details>

**Pull request merged**
