### PR TITLE
NDEV-3424: fix input field validation

### PR DESCRIPTION
**Pull request by gigimon**

### CODE REVIEW

**Comment by neonlabstech** [comment]
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getAccountInfo                    |  492563 |      0     |      0.413 |    0.00235326  |        0.001  |
| getSlot                           |  211057 |      0     |      0.37  |    0.0015654   |        0.001  |
| getMultipleAccounts               |  106409 |      0     |      0.408 |    0.00262104  |        0.001  |
| getTransaction                    |  104701 |      0     |      0.432 |    0.00875785  |        0.005  |
| getBlocks                         |   89081 |      0     |      0.064 |    0.00105809  |        0.001  |
| getLatestBlockhash                |   53901 |      0     |      0.253 |    0.00280696  |        0.001  |
| sendTransaction                   |   52584 |      0     |      0.414 |    0.0101804   |        0.006  |
| getBlockTime                      |   52374 |      0     |      0.277 |    0.000977928 |        0      |
| getBlock                          |   45768 |      0     |      0.409 |    0.00225291  |        0.002  |
| getBalance                        |   15213 |      0     |      0.268 |    0.00248196  |        0.001  |
| getSignatureStatuses              |    1401 |      0     |      0.167 |    0.00311849  |        0.001  |
| getVersion                        |     723 |      0     |      0.043 |    0.00256985  |        0.001  |
| isBlockhashValid                  |     682 |      0     |      0.088 |    0.0010044   |        0      |
| simulateTransaction               |     491 |      0     |      0.005 |    0.00137067  |        0.001  |
| getSignaturesForAddress           |      61 |      0.001 |      0.005 |    0.0022623   |        0.002  |
| requestAirdrop                    |      32 |      0     |      0.002 |    0.00103125  |        0.001  |
| getHealth                         |       3 |      0     |      0.012 |    0.00433333  |        0.001  |
| getTokenAccountBalance            |       3 |      0     |      0.001 |    0.000333333 |        0      |
| getFirstAvailableBlock            |       2 |      0     |      0.001 |    0.0005      |        0.0005 |
| getMinimumBalanceForRentExemption |       1 |      0.009 |      0.009 |    0.009       |        0.009  |
| getClusterNodes                   |       1 |      0.001 |      0.001 |    0.001       |        0.001  |

</details>

**Comment by afalaleev** [comment]
For what this PR?
Right now, a user can pass data in `data` or `input` parameter.
This PR removes `input` variant and accept only `data` variant.

**Review by afalaleev — CHANGES_REQUESTED** [review]
For what this PR?
Right now, a user can pass data in `data` or `input` parameter.
This PR removes the `input` variant and allows only the `data` variant.

**Comment by gigimon** [comment]
@afalaleev it's analog for this fix https://github.com/neonlabsorg/neon-proxy.py/commit/4119abea8f4589fda9cecef5cbecf7346c7de430 
Right now I got error if provide input and data (it's cast behavior)

**Comment by afalaleev** [comment]
This PR breaks the compatibility with new clients.
This is the correct fix: fa4509a16f3fa8b17d532bf566685bc6601aa4d3

**Pull request closed without merging**
