### PR TITLE
CI refactoring

### PR DESCRIPTION
**Pull request by kristinaNikolaevaa**

### CODE REVIEW

**Comment by neonlabstech** [comment]
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getAccountInfo                    |   58393 |          0 |      0.083 |    0.0011885   |         0     |
| getSlot                           |   56475 |          0 |      0.174 |    0.000773829 |         0     |
| getBlocks                         |   22946 |          0 |      0.14  |    0.000590953 |         0     |
| getBlock                          |   15084 |          0 |      0.054 |    0.00131059  |         0.001 |
| getMultipleAccounts               |   13941 |          0 |      0.13  |    0.00166165  |         0.001 |
| getTransaction                    |    8073 |          0 |      0.096 |    0.00796668  |         0.003 |
| getBlockTime                      |    6315 |          0 |      0.06  |    0.000429454 |         0     |
| sendTransaction                   |    5216 |          0 |      0.376 |    0.00646127  |         0.003 |
| getLatestBlockhash                |    4990 |          0 |      0.109 |    0.00202104  |         0.001 |
| getBalance                        |    1825 |          0 |      0.068 |    0.00129041  |         0.001 |
| getSignatureStatuses              |    1110 |          0 |      0.065 |    0.0010955   |         0     |
| getVersion                        |     581 |          0 |      0.022 |    0.000796902 |         0     |
| isBlockhashValid                  |     537 |          0 |      0.012 |    0.0003054   |         0     |
| getSignaturesForAddress           |      64 |          0 |      0.002 |    0.00125     |         0.001 |
| simulateTransaction               |      38 |          0 |      0.001 |    0.000131579 |         0     |
| requestAirdrop                    |      32 |          0 |      0.002 |    0.0006875   |         0.001 |
| getTokenAccountBalance            |       4 |          0 |      0.001 |    0.00025     |         0     |
| getHealth                         |       3 |          0 |      0.001 |    0.000333333 |         0     |
| getFirstAvailableBlock            |       2 |          0 |      0     |    0           |         0     |
| getMinimumBalanceForRentExemption |       1 |          0 |      0     |    0           |         0     |
| getClusterNodes                   |       1 |          0 |      0     |    0           |         0     |

</details>

**Comment by neonlabstech** [comment]
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getSlot                           |   64545 |      0     |      0.107 |    0.000876737 |        0      |
| getAccountInfo                    |   58542 |      0     |      0.126 |    0.00126205  |        0      |
| getBlocks                         |   25869 |      0     |      0.089 |    0.000611504 |        0      |
| getBlock                          |   16757 |      0     |      0.027 |    0.00128836  |        0.001  |
| getMultipleAccounts               |   14472 |      0     |      0.115 |    0.00193463  |        0.001  |
| getTransaction                    |    8012 |      0     |      0.343 |    0.0117207   |        0.004  |
| getBlockTime                      |    6281 |      0     |      0.072 |    0.000503741 |        0      |
| sendTransaction                   |    5204 |      0     |      0.132 |    0.00916583  |        0.004  |
| getLatestBlockhash                |    4972 |      0     |      0.213 |    0.00301368  |        0.001  |
| getBalance                        |    1828 |      0     |      0.037 |    0.00136379  |        0      |
| getSignatureStatuses              |    1092 |      0     |      0.074 |    0.000973443 |        0      |
| getVersion                        |     588 |      0     |      0.084 |    0.0017415   |        0      |
| isBlockhashValid                  |     528 |      0     |      0.047 |    0.000422348 |        0      |
| getSignaturesForAddress           |      58 |      0     |      0.002 |    0.00117241  |        0.001  |
| simulateTransaction               |      38 |      0     |      0.001 |    0.000315789 |        0      |
| requestAirdrop                    |      32 |      0     |      0.001 |    0.00053125  |        0.001  |
| getTokenAccountBalance            |      12 |      0     |      0.056 |    0.00508333  |        0.0005 |
| getHealth                         |       3 |      0     |      0.087 |    0.029       |        0      |
| getFirstAvailableBlock            |       2 |      0     |      0.001 |    0.0005      |        0.0005 |
| getMinimumBalanceForRentExemption |       1 |      0.001 |      0.001 |    0.001       |        0.001  |
| getClusterNodes                   |       1 |      0.001 |      0.001 |    0.001       |        0.001  |

</details>

**Comment by neonlabstech** [comment]
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getSlot                           |   63321 |      0     |      0.112 |    0.000891789 |         0     |
| getAccountInfo                    |   58739 |      0     |      0.125 |    0.00167136  |         0     |
| getBlocks                         |   26061 |      0     |      0.046 |    0.000669775 |         0.001 |
| getBlock                          |   16910 |      0     |      0.044 |    0.00156162  |         0.001 |
| getMultipleAccounts               |   14070 |      0     |      0.159 |    0.00203802  |         0.001 |
| getTransaction                    |    8076 |      0     |      0.171 |    0.0110604   |         0.004 |
| getBlockTime                      |    6246 |      0     |      0.128 |    0.000574127 |         0     |
| sendTransaction                   |    5217 |      0     |      0.152 |    0.00785317  |         0.003 |
| getLatestBlockhash                |    4995 |      0     |      0.11  |    0.00221301  |         0.001 |
| getBalance                        |    1833 |      0     |      0.158 |    0.00178342  |         0.001 |
| getSignatureStatuses              |    1100 |      0     |      0.079 |    0.00115545  |         0     |
| getVersion                        |     574 |      0     |      0.04  |    0.0015993   |         0     |
| isBlockhashValid                  |     532 |      0     |      0.021 |    0.000586466 |         0     |
| getSignaturesForAddress           |      58 |      0     |      0.004 |    0.0012931   |         0.001 |
| simulateTransaction               |      38 |      0     |      0.001 |    0.000447368 |         0     |
| requestAirdrop                    |      32 |      0     |      0.002 |    0.000875    |         0.001 |
| getHealth                         |       3 |      0     |      0.001 |    0.000333333 |         0     |
| getTokenAccountBalance            |       3 |      0     |      0     |    0           |         0     |
| getFirstAvailableBlock            |       2 |      0.001 |      0.001 |    0.001       |         0.001 |
| getMinimumBalanceForRentExemption |       1 |      0     |      0     |    0           |         0     |
| getClusterNodes                   |       1 |      0     |      0     |    0           |         0     |

</details>

**Comment by neonlabstech** [comment]
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getAccountInfo                    |   57899 |      0     |      0.107 |    0.00129007  |        0      |
| getSlot                           |   57050 |      0     |      0.288 |    0.000817441 |        0      |
| getBlocks                         |   22303 |      0     |      0.096 |    0.000603686 |        0      |
| getBlock                          |   14444 |      0     |      0.04  |    0.00129265  |        0.001  |
| getMultipleAccounts               |   13522 |      0     |      0.113 |    0.00182976  |        0.001  |
| getTransaction                    |    8013 |      0     |      0.295 |    0.0105214   |        0.004  |
| getBlockTime                      |    6162 |      0     |      0.102 |    0.000458617 |        0      |
| sendTransaction                   |    5161 |      0     |      0.102 |    0.00711258  |        0.003  |
| getLatestBlockhash                |    4965 |      0     |      0.197 |    0.00201329  |        0.001  |
| getBalance                        |    1815 |      0     |      0.05  |    0.00132287  |        0      |
| getSignatureStatuses              |    1092 |      0     |      0.081 |    0.00119139  |        0      |
| getVersion                        |     578 |      0     |      0.038 |    0.00139792  |        0      |
| isBlockhashValid                  |     528 |      0     |      0.017 |    0.000359848 |        0      |
| getSignaturesForAddress           |      59 |      0     |      0.011 |    0.00157627  |        0.001  |
| simulateTransaction               |      38 |      0     |      0.001 |    0.000394737 |        0      |
| requestAirdrop                    |      32 |      0     |      0.001 |    0.0006875   |        0.001  |
| getTokenAccountBalance            |       7 |      0     |      0.002 |    0.000714286 |        0.001  |
| getHealth                         |       3 |      0     |      0.009 |    0.00333333  |        0.001  |
| getFirstAvailableBlock            |       2 |      0     |      0.001 |    0.0005      |        0.0005 |
| getMinimumBalanceForRentExemption |       1 |      0     |      0     |    0           |        0      |
| getClusterNodes                   |       1 |      0.003 |      0.003 |    0.003       |        0.003  |

</details>

**Comment by neonlabstech** [comment]
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getAccountInfo                    |   58122 |       0    |      0.155 |    0.00156108  |         0     |
| getSlot                           |   57189 |       0    |      0.195 |    0.00092551  |         0     |
| getBlocks                         |   22201 |       0    |      0.177 |    0.000707626 |         0.001 |
| getBlock                          |   14398 |       0    |      0.043 |    0.00148917  |         0.001 |
| getMultipleAccounts               |   13337 |       0    |      0.14  |    0.00205458  |         0.001 |
| getTransaction                    |    8051 |       0    |      0.164 |    0.0110775   |         0.004 |
| getBlockTime                      |    6249 |       0    |      0.161 |    0.000603937 |         0     |
| sendTransaction                   |    5187 |       0    |      0.155 |    0.00815134  |         0.004 |
| getLatestBlockhash                |    4983 |       0    |      0.303 |    0.00247762  |         0.001 |
| getBalance                        |    1823 |       0    |      0.149 |    0.00154745  |         0.001 |
| getSignatureStatuses              |    1095 |       0    |      0.139 |    0.00145297  |         0.001 |
| getVersion                        |     572 |       0    |      0.037 |    0.00144755  |         0     |
| isBlockhashValid                  |     529 |       0    |      0.015 |    0.000429112 |         0     |
| getSignaturesForAddress           |      61 |       0    |      0.012 |    0.00168852  |         0.001 |
| simulateTransaction               |      38 |       0    |      0.001 |    0.000394737 |         0     |
| requestAirdrop                    |      32 |       0    |      0.002 |    0.0009375   |         0.001 |
| getHealth                         |       3 |       0    |      0.001 |    0.000666667 |         0.001 |
| getTokenAccountBalance            |       3 |       0    |      0     |    0           |         0     |
| getFirstAvailableBlock            |       2 |       0    |      0     |    0           |         0     |
| getMinimumBalanceForRentExemption |       1 |       0    |      0     |    0           |         0     |
| getClusterNodes                   |       1 |       0.06 |      0.06  |    0.06        |         0.06  |

</details>

**Review by IvanAdamovNeon — APPROVED** [review]

**Pull request merged**
